name: kiarra
description: "A new Flutter project."
publish_to: 'none' # Hapus ini jika ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/images/logoDana.png
    - assets/images/logoShoppeePay.png
    - assets/images/logoOVO.png
